FROM python:3.10.20-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    curl \
    && rm -rf /var/lib/apt/lists/*

RUN curl https://getmic.ro | bash && \
    mv micro /usr/local/bin/

ENV MYSQL_HOST=mysql \
    MYSQL_PORT=3306 \
    MYSQL_USER=root \
    MYSQL_PASSWORD=12345678 \
    SYSTEM_DB_NAME=data_preprocess \
    MYSQL_DB=test_db \
    CK_HOST=clickhouse \
    CK_PORT=9000 \
    CK_USER=default \
    CK_PASSWORD=admin \
    MINIO_ENDPOINT=http://minio:9000 \
    MINIO_ROOT_USER=minioadmin \
    MINIO_ROOT_PASSWORD=minioadmin \
    API_V1_STR=/api/v1 \
    PROJECT_NAME="Data Preprocessing System"

COPY backend/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple

COPY backend/ .

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
